Repository dotnet/core-setup, pull requests merged in 2018-10, with the labels that each got.

#4445 [release/2.1] Enable Tizen CI
  cross/armel/tizen-fetch.sh
  netci.groovy
  tools-local/scripts/arm32_ci_script.sh
Labels: Servicing-approved, area-Infrastructure

#4590 Replace MIT License with .NET Library EULA in setup bundle
  src/pkg/packaging/windows/sharedframework/bundle.thm
  src/pkg/packaging/windows/sharedframework/bundle.wxl
Labels: Servicing-approved, area-Setup

#4588 Replace MIT License with .NET Library EULA in setup bundle
  src/pkg/packaging/windows/sharedframework/bundle.thm
  src/pkg/packaging/windows/sharedframework/bundle.wxl
Labels: area-Setup

#4645 Fix http link to https (#4635)
  src/corehost/common/utils.h
Labels: Servicing-approved

#4632 Updating the host's help messages; modifying tests.
  src/corehost/cli/fxr/fx_muxer.cpp
  src/corehost/cli/fxr/sdk_resolver.cpp
  src/test/HostActivationTests/GivenThatICareAboutMultilevelSDKLookup.cs
Labels: area-SDK

#4574 [release/2.2] Startup hook host functionality
  Documentation/design-docs/host-startup-hook.md
  src/corehost/cli/hostpolicy.cpp
  src/test/Assets/TestProjects/LightupLib/Program.cs
  src/test/Assets/TestProjects/PortableAppWithMissingRef/PortableAppWithMissingRef.csproj
  src/test/Assets/TestProjects/PortableAppWithMissingRef/Program.cs
  src/test/Assets/TestProjects/PortableAppWithMissingRef/SharedLibrary/ReferenceLibrary.csproj
  src/test/Assets/TestProjects/PortableAppWithMissingRef/SharedLibrary/SharedLibrary.cs
  src/test/Assets/TestProjects/StartupHook/StartupHook.cs
  src/test/Assets/TestProjects/StartupHook/StartupHook.csproj
  src/test/Assets/TestProjects/StartupHookFake/StartupHookFake.csproj
  src/test/Assets/TestProjects/StartupHookFake/StartupHookInvalidAssembly.dll
  src/test/Assets/TestProjects/StartupHookWithAssemblyResolver/SharedLibrary/SharedLibrary.cs
  src/test/Assets/TestProjects/StartupHookWithAssemblyResolver/SharedLibrary/SharedLibrary.csproj
  src/test/Assets/TestProjects/StartupHookWithAssemblyResolver/StartupHookWithAssemblyResolver.cs
  src/test/Assets/TestProjects/StartupHookWithAssemblyResolver/StartupHookWithAssemblyResolver.csproj
  src/test/Assets/TestProjects/StartupHookWithDependency/StartupHookWithDependency.cs
  src/test/Assets/TestProjects/StartupHookWithDependency/StartupHookWithDependency.csproj
  src/test/Assets/TestProjects/StartupHookWithInstanceMethod/StartupHookWithInstanceMethod.cs
  src/test/Assets/TestProjects/StartupHookWithInstanceMethod/StartupHookWithInstanceMethod.csproj
  src/test/Assets/TestProjects/StartupHookWithMultipleIncorrectSignatures/StartupHookWithMultipleIncorrectSignatures.cs
  src/test/Assets/TestProjects/StartupHookWithMultipleIncorrectSignatures/StartupHookWithMultipleIncorrectSignatures.csproj
  src/test/Assets/TestProjects/StartupHookWithNonPublicMethod/StartupHookWithNonPublicMethod.cs
  src/test/Assets/TestProjects/StartupHookWithNonPublicMethod/StartupHookWithNonPublicMethod.csproj
  src/test/Assets/TestProjects/StartupHookWithOverload/StartupHookWithOverload.cs
  src/test/Assets/TestProjects/StartupHookWithOverload/StartupHookWithOverload.csproj
  src/test/Assets/TestProjects/StartupHookWithParameter/StartupHookWithParameter.cs
  src/test/Assets/TestProjects/StartupHookWithParameter/StartupHookWithParameter.csproj
  src/test/Assets/TestProjects/StartupHookWithReturnType/StartupHookWithReturnType.cs
  src/test/Assets/TestProjects/StartupHookWithReturnType/StartupHookWithReturnType.csproj
  src/test/Assets/TestProjects/StartupHookWithoutInitializeMethod/StartupHookWithoutInitializeMethod.cs
  src/test/Assets/TestProjects/StartupHookWithoutInitializeMethod/StartupHookWithoutInitializeMethod.csproj
  src/test/Assets/TestProjects/StartupHookWithoutStartupHookType/StartupHookWithoutStartupHookType.cs
  src/test/Assets/TestProjects/StartupHookWithoutStartupHookType/StartupHookWithoutStartupHookType.csproj
  src/test/HostActivationTests/GivenThatICareAboutStartupHooks.cs
  src/test/HostActivationTests/HostActivationTests.csproj
  src/test/TestUtils/Assertions/CommandResultAssertions.cs
  src/test/TestUtils/TestProjectFixture.cs
Labels: Servicing-more-info

#4699 disable crossgen on FreeBSD for now
  dir.props
Labels: os-freebsd
