Repository dotnet/core-setup, pull requests merged in 2018-05, with the labels that each got.

#4132 [1.1] Update distro support
  build_projects/Microsoft.DotNet.Cli.Build.Framework/project.json
  build_projects/dotnet-host-build/project.json
  build_projects/shared-build-targets-utils/project.json
  build_projects/update-dependencies/project.json
  buildpipeline/Core-Setup-Fedora28-x64.json
  buildpipeline/Core-Setup-OpenSuse42.1-x64.json
  buildpipeline/pipeline.json
  packaging/deb/dotnet-sharedframework-debian_config.json
  pkg/deps/project.json
  pkg/dir.props
  pkg/projects/Microsoft.NETCore.App/project.json
  pkg/projects/Microsoft.NETCore/project.json
  scripts/docker/debian.9/Dockerfile
  scripts/docker/fedora.27/Dockerfile
  scripts/docker/fedora.28/Dockerfile
  tools/independent/RuntimeGraphGenerator/project.json
Labels: area-Setup

#4136 Update DependencyModel to latest
  tools-local/tasks/core-setup.tasks.csproj
Labels: * NO MERGE *

#3954 [Port #2501 to release/1.1] AppBaseCompilationAssemblyResolver shouldn't throw.
  src/Microsoft.Extensions.DependencyModel/Resolution/AppBaseCompilationAssemblyResolver.cs
  test/Microsoft.Extensions.DependencyModel.Tests/AppBaseResolverTests.cs
Labels: Servicing-Approved-1.1.9

#4170 [1.1] Remove Debian9 from PublishTargets check
  build_projects/dotnet-host-build/PublishTargets.cs
Labels: bug

#4174 [1.1] Add NUGET_FEED_URL to env-vars in build pipelines
  buildpipeline/Core-Setup-CentOS-x64.json
  buildpipeline/Core-Setup-Debian8-x64.json
  buildpipeline/Core-Setup-Debian9-x64.json
  buildpipeline/Core-Setup-Fedora24-x64.json
  buildpipeline/Core-Setup-Fedora27-x64.json
  buildpipeline/Core-Setup-Fedora28-x64.json
  buildpipeline/Core-Setup-OSX-x64.json
  buildpipeline/Core-Setup-OpenSuse42.1-x64.json
  buildpipeline/Core-Setup-OpenSuse42.3-x64.json
  buildpipeline/Core-Setup-RHEL7-x64.json
  buildpipeline/Core-Setup-Ubuntu14.04-x64.json
  buildpipeline/Core-Setup-Ubuntu16.04-x64.json
  buildpipeline/Core-Setup-Ubuntu18.04-x64.json
Labels: area-Infrastructure, bug

#4180 [1.1] Build All packages for servicing
  pkg/projects/packages.builds
Labels: area-Infrastructure, bug
