Repository dotnet/core-setup, pull requests merged in 2018-02, with the labels that each got.

#3696 Block X64 Bundle package on X86 OS
  src/pkg/packaging/windows/sharedframework/bundle.wxs
Labels: area-Setup

#3725 Update BuildTools to 2.1.0-preview2-02522-03
  BuildToolsVersion.txt
  dependencies.props
Labels: area-Infrastructure

#3737 Fix issue with deps resolver and duplicate assembly names
  src/corehost/cli/deps_entry.h
  src/corehost/cli/deps_format.cpp
  src/corehost/cli/deps_resolver.cpp
Labels: blocking-clean-ci

#3738 [release/2.1] Update BuildTools to 2.1.0-preview1-02523-01
  BuildToolsVersion.txt
  dependencies.props
Labels: area-Infrastructure
