Repository dotnet/core-setup, pull requests merged in 2019-11, with the labels that each got.

#8714 Use PackageLicenseExpression for Setup nupkgs
  src/pkg/Directory.Build.props
Labels: area-Infrastructure

#8733 D.B.props absolute path condition check
  tools-local/Directory.Build.props
Labels: area-Infrastructure

#8767 Allow ManPagesDir override, handle error better (consolidation)
  src/pkg/packaging/deb/package.targets
  src/pkg/packaging/rpm/package.targets
Labels: area-Infrastructure

#8780 Backport pipeline changes
  azure-pipelines.yml
  eng/pipelines/jobs/bash-build.yml
  eng/pipelines/jobs/osx-build.yml
  eng/pipelines/jobs/steps/build-linux-package.yml
  eng/pipelines/jobs/steps/upload-job-artifacts.yml
  eng/pipelines/jobs/windows-build.yml
  eng/pipelines/stages/publish.yml
  src/corehost/build.sh
  src/signing/Directory.Build.props
Labels: area-Infrastructure

#8791 Remove step to delete broken symlink in AzDO pipeline YAML
  eng/pipelines/jobs/steps/upload-job-artifacts.yml
Labels: area-Infrastructure

#8797 Remove of root cross folder in favor of eng/common/cross
  cross/android/arm/toolchain.cmake
  cross/android/arm/tryrun.cmake
  cross/android/arm64/toolchain.cmake
  cross/android/arm64/tryrun.cmake
  cross/arm/sources.list.bionic
  cross/arm/sources.list.jessie
  cross/arm/sources.list.trusty
  cross/arm/sources.list.vivid
  cross/arm/sources.list.wily
  cross/arm/sources.list.xenial
  cross/arm/sources.list.zesty
  cross/arm/trusty-lttng-2.4.patch
  cross/arm/trusty.patch
  cross/arm64/sources.list.bionic
  cross/arm64/sources.list.trusty
  cross/arm64/sources.list.vivid
  cross/arm64/sources.list.wily
  cross/arm64/sources.list.xenial
  cross/arm64/sources.list.zesty
  cross/armel/sources.list.jessie
  cross/armel/tizen-build-rootfs.sh
  cross/armel/tizen-fetch.sh
  cross/armel/tizen/tizen-dotnet.ks
  cross/armel/tizen/tizen.patch
  cross/build-android-rootfs.sh
  cross/build-rootfs.sh
  cross/toolchain.cmake
  cross/tryrun.cmake
  cross/x86/sources.list.bionic
  cross/x86/sources.list.trusty
  cross/x86/sources.list.vivid
  cross/x86/sources.list.wily
  cross/x86/sources.list.xenial
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/cross/toolchain.cmake
  global.json
  src/corehost/build.sh
  tools-local/scripts/arm32_ci_script.sh
Labels: area-Infrastructure

#8800 Fix template path in publish.yml
  azure-pipelines.yml
  eng/pipelines/stages/publish.yml
Labels: area-Infrastructure

#8809 Fix visibility of ComHost type in HostModel.
  src/managed/Microsoft.NET.HostModel/ComHost/ComHost.cs
Labels: area-HostModel

#8812 Fix calling convention of load_in_memory_assembly_fn.
  src/corehost/cli/ijwhost/ijwhost.h
Labels: area-Host, bug

#8718 [release/3.1] Use PackageLicenseExpression for Setup nupkgs
  src/pkg/Directory.Build.props
Labels: Servicing-approved, area-Infrastructure

#8802 [release/3.1] Update tests to explicit set/unset environment variables as they expect
  src/test/HostActivation.Tests/CommandExtensions.cs
  src/test/HostActivation.Tests/FrameworkResolution/FrameworkResolutionBase.cs
  src/test/HostActivation.Tests/MockCoreClrSanity.cs
  src/test/HostActivation.Tests/NativeHosting/Comhost.cs
  src/test/HostActivation.Tests/NativeHosting/ComponentActivation.cs
  src/test/HostActivation.Tests/NativeHosting/HostContext.cs
  src/test/HostActivation.Tests/NativeHosting/Nethost.cs
  src/test/HostActivation.Tests/NativeHosting/SharedTestStateBase.cs
  src/test/HostActivation.Tests/PortableAppActivation.cs
  src/test/TestUtils/Command.cs
  src/test/TestUtils/DotNetCli.cs
Labels: tell-mode

#8813 [release/3.1] Fix calling convention of load_in_memory_assembly_fn.
  src/corehost/cli/ijwhost/ijwhost.h
Labels: Servicing-consider, area-Host, bug

#8844 Fix the validation channel's variable name
  azure-pipelines.yml
Labels: area-Infrastructure

#8842 Update CoreCLR override to use the sharedFramework output folder instead of comparing with packages
  src/pkg/projects/netcoreapp/src/localnetcoreapp.override.targets
  src/pkg/projects/netcoreapp/src/netcoreapp.depproj
Labels: area-Infrastructure

#8846 Add automatic SDL validation
  azure-pipelines.yml
  eng/pipelines/stages/publish.yml
Labels: area-Infrastructure-installer, post-consolidation

#8811 [release/3.0] Update tests to explicit set/unset environment variables as they expect
  src/test/HostActivation.Tests/CommandExtensions.cs
  src/test/HostActivation.Tests/FrameworkResolution/FrameworkResolutionBase.cs
  src/test/HostActivation.Tests/MockCoreClrSanity.cs
  src/test/HostActivation.Tests/NativeHosting/Comhost.cs
  src/test/HostActivation.Tests/NativeHosting/ComponentActivation.cs
  src/test/HostActivation.Tests/NativeHosting/HostContext.cs
  src/test/HostActivation.Tests/NativeHosting/Nethost.cs
  src/test/HostActivation.Tests/NativeHosting/SharedTestStateBase.cs
  src/test/HostActivation.Tests/PortableAppActivation.cs
  src/test/TestUtils/Command.cs
  src/test/TestUtils/DotNetCli.cs
Labels: area-Host, tell-mode, test bug

#8625 [release/3.0] Remove signature on MAC AppHost
  src/managed/Microsoft.NET.HostModel/AppHost/AppHostMachOFormatException.cs
  src/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
  src/managed/Microsoft.NET.HostModel/AppHost/MachOUtils.cs
Labels: Servicing-approved, area-HostModel

#8827 [release/3.0] Add servicing config: project skip infrastructure
  eng/Versions.props
  src/pkg/packaging-tools/framework.packaging.targets
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/projects/netstandard/pkg/Directory.Build.props
  src/test/Microsoft.DotNet.CoreSetup.Packaging.Tests/NETCoreTests.cs
  src/test/Microsoft.DotNet.CoreSetup.Packaging.Tests/NETStandardTests.cs
  src/test/Microsoft.DotNet.CoreSetup.Packaging.Tests/WindowsDesktopTests.cs
Labels: Servicing-approved, area-Infrastructure-installer

#7968 [release/2.1] Generate VS insertion MSI nupkgs
  BranchInfo.props
  publish/dir.props
  publish/publish.proj
  src/pkg/packaging/dir.proj
  src/pkg/packaging/windows/vscomponents/VS.Redist.Common.Component.nuspec
  src/pkg/packaging/windows/vscomponents/generatenupkg.ps1
Labels: Servicing-approved, area-Infrastructure-installer

#8571 [release/3.0] Fix CoreFX compatibility package versions and auto-update
  eng/Versions.props
  src/pkg/projects/windowsdesktop/src/windowsdesktop.depproj
Labels: Servicing-approved, area-Infrastructure-installer
