Repository dotnet/core-setup, pull requests merged in 2019-10, with the labels that each got.

#8410 Switch core-setup to use VS2019.
  eng/jobs/windows-build.yml
Labels: area-Infrastructure

#8425 [release/3.0] Stabilize package versions for 3.0.1
  eng/Versions.props
Labels: * NO MERGE *

#8462 Fix bundle failing to extract empty file.
  src/corehost/cli/apphost/bundle/file_entry.cpp
  src/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundledAppWithSubDirs.cs
Labels: area-Host

#8448 Enable using Live-live builds of CoreCLR and CoreFX with Core-Setup
  Documentation/building/local-coreclr-corefx.md
  src/pkg/packaging-tools/framework.dependency.targets
  src/pkg/projects/netcoreapp/src/localnetcoreapp.override.targets
  src/pkg/projects/netcoreapp/src/netcoreapp.depproj
Labels: area-Infrastructure

#8470 [release/3.1] Fix bundle failing to extract empty file
  src/corehost/cli/apphost/bundle/file_entry.cpp
  src/test/BundleTests/AppHost.Bundle.Tests/BundledAppWithSubDirs.cs
Labels: area-Host, ask-mode

#8468 Enable building for arm64 on arm64
  Directory.Build.props
  src/pkg/packaging-tools/framework.dependency.targets
Labels: area-Infrastructure

#8301 [release/3.0] Add missing "--ci" option to Linux build
  eng/jobs/steps/build-linux-package.yml
Labels: area-Infrastructure, tell-mode

#8503 Upgrade CMake to 3.14
  Documentation/building/windows-instructions.md
  azure-pipelines.yml
  src/corehost/CMakeLists.txt
  src/corehost/Windows/gen-buildsys-win.bat
  src/corehost/build.sh
  src/corehost/cli/ijwhost/CMakeLists.txt
  src/functions.cmake
Labels: area-Infrastructure

#8367 Self contained component fx validation
  src/corehost/cli/fxr/corehost_init.cpp
  src/corehost/cli/fxr/corehost_init.h
  src/corehost/cli/fxr/fx_muxer.cpp
  src/corehost/cli/fxr/host_context.cpp
  src/corehost/cli/fxr/host_context.h
  src/corehost/cli/runtime_config.cpp
  src/corehost/cli/runtime_config.h
  src/test/HostActivation.Tests/FrameworkResolution/FrameworkResolutionBase.cs
  src/test/HostActivation.Tests/FrameworkResolution/IncludedFrameworksSettings.cs
  src/test/HostActivation.Tests/NativeHosting/HostContext.cs
  src/test/HostActivation.Tests/RuntimeConfig.cs
  src/test/HostActivation.Tests/StandaloneAppActivation.cs
  src/test/TestUtils/AppHostExtensions.cs
  src/test/TestUtils/TestUtils.csproj
Labels: area-Host

#8508 [release/3.1] Include .NET Core Runtime in WindowsDesktop bundle
  src/pkg/projects/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.Bundle.bundleproj
Labels: area-Setup, ask-mode

#8547 Use shared tooling to build the .NET Core shared framework
  Subsets.props
  eng/Version.Details.xml
  global.json
  src/pkg/Directory.Build.props
  src/pkg/Directory.Build.targets
  src/pkg/packaging-tools/acquire-nuget-exe/acquire-nuget-exe.proj
  src/pkg/packaging-tools/acquire-wix/acquire-wix.proj
  src/pkg/packaging-tools/framework.bundle.props
  src/pkg/packaging-tools/framework.bundle.targets
  src/pkg/packaging-tools/framework.dependency.props
  src/pkg/packaging-tools/framework.dependency.targets
  src/pkg/packaging-tools/framework.packaging.props
  src/pkg/packaging-tools/framework.packaging.targets
  src/pkg/packaging-tools/framework.sharedfx.props
  src/pkg/packaging-tools/framework.sharedfx.targets
  src/pkg/packaging-tools/installer.targets
  src/pkg/packaging-tools/packaging-tools.props
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/skip.GetPackageReport.targets
  src/pkg/packaging-tools/windows/bundle/bundle.wxs
  src/pkg/packaging-tools/windows/bundle/dummyEula.rtf
  src/pkg/packaging-tools/windows/eula.rtf
  src/pkg/packaging-tools/windows/product/breadcrumbstorefolder.wxs
  src/pkg/packaging-tools/windows/product/product.common.wxi
  src/pkg/packaging-tools/windows/product/product.wxs
  src/pkg/packaging-tools/windows/product/provider.wxs
  src/pkg/packaging-tools/windows/product/registrykeys.wxs
  src/pkg/packaging-tools/windows/product/sharedfxdir.wxs
  src/pkg/packaging-tools/windows/product/werrelatedkeys.wxs
  src/pkg/packaging-tools/windows/variables.wxi
  src/pkg/packaging-tools/windows/vs/VS.Redist.Common.Component.nuspec
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/Directory.Build.props
  src/pkg/projects/Directory.Build.targets
Labels: area-Setup

#8540 [release/3.1] Self contained component fx validation
  src/corehost/cli/fxr/corehost_init.cpp
  src/corehost/cli/fxr/corehost_init.h
  src/corehost/cli/fxr/fx_muxer.cpp
  src/corehost/cli/fxr/host_context.cpp
  src/corehost/cli/fxr/host_context.h
  src/corehost/cli/runtime_config.cpp
  src/corehost/cli/runtime_config.h
  src/test/HostActivation.Tests/FrameworkResolution/FrameworkResolutionBase.cs
  src/test/HostActivation.Tests/FrameworkResolution/IncludedFrameworksSettings.cs
  src/test/HostActivation.Tests/NativeHosting/HostContext.cs
  src/test/HostActivation.Tests/RuntimeConfig.cs
  src/test/HostActivation.Tests/StandaloneAppActivation.cs
  src/test/TestUtils/AppHostExtensions.cs
  src/test/TestUtils/TestUtils.csproj
Labels: area-Host, ask-mode

#8510 Set apphost and bundle file permission to 755₈
  eng/Version.Details.xml
  eng/Versions.props
  src/corehost/CMakeLists.txt
  src/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
  src/test/Directory.Build.props
  src/test/HostActivation.Tests/HostActivation.Tests.csproj
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/AppHostUpdateTests.cs
  src/test/TestUtils/Command.cs
  src/test/TestUtils/TestUtils.csproj
Labels: area-HostModel

#8497 Specify sdk version, use nuget cache
  eng/configure-toolset.ps1
  eng/configure-toolset.sh
  global.json
  src/test/HostActivation.Tests/MultilevelSDKLookup.cs
  src/test/HostActivation.Tests/SDKLookup.cs
Labels: area-Infrastructure

#8509 Show error dialog for missing runtime/framework
  src/corehost/cli/apphost/CMakeLists.txt
  src/corehost/cli/apphost/apphost.windows.cpp
  src/corehost/cli/apphost/apphost.windows.h
  src/corehost/cli/deps_format.cpp
  src/corehost/cli/fxr/fx_resolver.messages.cpp
  src/corehost/cli/fxr_resolver.cpp
  src/corehost/common/utils.cpp
  src/corehost/common/utils.h
  src/corehost/corehost.cpp
  src/test/HostActivation.Tests/Constants.cs
  src/test/HostActivation.Tests/PortableAppActivation.cs
Labels: area-Host

#8593 Changes to prepare for consolidation
  Directory.Build.props
  LICENSE
  eng/Version.Details.xml
  global.json
  publish/prepare-artifacts.proj
  src/corehost/build.cmd
  src/corehost/build.proj
  src/corehost/build.sh
  src/managed/CommonManaged.props
  src/pkg/Directory.Build.props
  src/pkg/packaging/installers.proj
  src/pkg/packaging/pack-managed.proj
  src/pkg/packaging/vs-insertion-packages.proj
  src/pkg/projects/Directory.Build.props
  src/pkg/projects/Microsoft.NETCore.DotNetHost/Microsoft.NETCore.DotNetHost.pkgproj
  src/test/PrepareTestAssets/PrepareTestAssets.proj
Labels: area-Infrastructure

#8591 [release/3.1] Show error dialog for missing runtime/framework
  src/corehost/cli/apphost/CMakeLists.txt
  src/corehost/cli/apphost/apphost.windows.cpp
  src/corehost/cli/apphost/apphost.windows.h
  src/corehost/cli/deps_format.cpp
  src/corehost/cli/fxr/fx_resolver.messages.cpp
  src/corehost/cli/fxr_resolver.cpp
  src/corehost/common/utils.cpp
  src/corehost/common/utils.h
  src/corehost/corehost.cpp
  src/test/HostActivation.Tests/Constants.cs
  src/test/HostActivation.Tests/PortableAppActivation.cs
Labels: area-Host

#8621 Move signing dir under eng/. Remove usages of ProjectDir.
  Directory.Build.props
  eng/signing/Directory.Build.props
  eng/signing/Directory.Build.targets
  eng/signing/SignBinaries.proj
  eng/signing/SignBurnBundleFiles.proj
  eng/signing/SignBurnEngineFiles.proj
  eng/signing/SignFinalPackages.proj
  eng/signing/SignMsiFiles.proj
  publish/prepare-artifacts.proj
  src/pkg/Directory.Build.props
  src/pkg/packaging/Directory.Build.props
  src/pkg/packaging/deb/package.targets
  src/pkg/packaging/installers.proj
  src/pkg/packaging/pack-managed.proj
  src/pkg/packaging/rpm/package.targets
  src/pkg/packaging/vs-insertion-packages.proj
  src/pkg/projects/Directory.Build.props
  src/test/Directory.Build.props
Labels: area-Infrastructure

#8572 [release/3.1] Fix CoreFX compatibility package versions and auto-update
  eng/Versions.props
  src/pkg/projects/windowsdesktop/src/windowsdesktop.depproj
Labels: Servicing-approved, area-Infrastructure, ask-mode

#8641 Refactor TestProjects.props/targets lookup for consolidation
  src/test/Directory.Build.targets
  src/test/TestProjects.props
  src/test/TestProjects.targets
  src/test/TestUtils/RepoDirectoriesProvider.cs
  src/test/TestUtils/TestProjectFixture.cs
Labels: area-Infrastructure

#8655 Resolve test assets location via a test context variable.
  src/test/Assets/TestProjects/Directory.Build.props
  src/test/Assets/TestProjects/Directory.Build.targets
  src/test/Assets/TestUtils/MNADeprecationWorkaround.props
  src/test/Assets/TestUtils/TestProjects.props
  src/test/Assets/TestUtils/TestProjects.targets
  src/test/Directory.Build.targets
  src/test/HostActivation.Tests/MultilevelSDKLookup.cs
  src/test/HostActivation.Tests/SDKLookup.cs
  src/test/TestUtils/RepoDirectoriesProvider.cs
  src/test/TestUtils/TestProjectFixture.cs
Labels: area-Infrastructure

#8678 Add value of multilevel lookup to log
  src/corehost/common/utils.cpp
Labels: area-Host

#8693 Source-build patch: Use RefOnly prefix to pin ref only versions
  eng/Versions.props
  src/test/Microsoft.DotNet.CoreSetup.Packaging.Tests/Microsoft.DotNet.CoreSetup.Packaging.Tests.csproj
  tools-local/tasks/core-setup.tasks.csproj
Labels: area-Infrastructure

#8696 [release/3.1] Source-build patch: Use RefOnly prefix to pin ref only versions
  eng/Versions.props
  src/test/Microsoft.DotNet.CoreSetup.Packaging.Tests/Microsoft.DotNet.CoreSetup.Packaging.Tests.csproj
  tools-local/tasks/core-setup.tasks.csproj
Labels: area-Infrastructure, tell-mode

#8697 [release/3.0] Source-build patch: Use RefOnly prefix to pin ref only versions
  eng/Versions.props
  src/test/Microsoft.DotNet.CoreSetup.Packaging.Tests/Microsoft.DotNet.CoreSetup.Packaging.Tests.csproj
  tools-local/tasks/core-setup.tasks.csproj
Labels: Servicing-approved, area-Infrastructure
