Repository dotnet/core-setup, pull requests merged in 2019-09, with the labels that each got.

#7762 Make it more obvious what constitutes an invalid directory.
  src/corehost/common/longfile.windows.cpp
Labels: area-Host

#7868 Remove WPF IgnoredDuplicateType exceptions: improve validation
  src/pkg/projects/windowsdesktop/pkg/Microsoft.WindowsDesktop.App.pkgproj
Labels: area-Infrastructure

#7970 Remove WPF ignored duplicates: improve validation
  src/pkg/projects/windowsdesktop/pkg/Microsoft.WindowsDesktop.App.pkgproj
Labels: area-Infrastructure, tell-mode

#7959 Commonize symbol file discovery: fix symbol zip
  src/pkg/packaging-tools/framework.dependency.targets
  src/pkg/packaging-tools/framework.sharedfx.targets
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/projects/Directory.Build.targets
Labels: area-Infrastructure

#7990 [release/3.0] Fix macOS pkg IDs: include version to prevent unwanted in-place upgrade
  src/pkg/Directory.Build.targets
  src/pkg/packaging/osx/package.props
Labels: area-Infrastructure, tell-mode

#7994 Copy PTB NETCoreApp loc fix to WindowsDesktop
  src/pkg/projects/windowsdesktop/sfx/theme/1046/bundle.wxl
Labels: area-Setup

#7910 [release/3.0] Fix source-build patch and workaround arg
  src/pkg/packaging-tools/framework.sharedfx.targets
  src/pkg/projects/Directory.Build.props
  src/pkg/projects/windowsdesktop/Directory.Build.props
Labels: area-Infrastructure, tell-mode

#7995 [release/3.0] Fix CoreFX PDBs not being included in symbol archive zip/tarball
  src/pkg/packaging-tools/framework.dependency.targets
  src/pkg/packaging-tools/framework.sharedfx.targets
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/projects/Directory.Build.props
  src/pkg/projects/Directory.Build.targets
Labels: area-Infrastructure, tell-mode

#8000 [release/3.0] Localization update for pt-BR runtime installers
  src/pkg/projects/netcoreapp/sfx/theme/1046/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1046/bundle.wxl
Labels: area-Setup, ask-mode

#8105 Use IsShipping=false to keep VS insertion nupkgs unique
  Directory.Build.targets
  publish/Directory.Build.props
  publish/prepare-artifacts.proj
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/windows/wix.targets
  src/test/Directory.Build.targets
Labels: area-Infrastructure

#8155 Fix NonShipping packages to always be unstable
  src/pkg/projects/Directory.Build.targets
  src/pkg/projects/netcoreapp/pkg/legacy/Directory.Build.props
  src/pkg/projects/netcoreapp/pkg/workaround/Microsoft.NETCore.App.pkgproj
  src/pkg/projects/windowsdesktop/pkg/Microsoft.WindowsDesktop.App.pkgproj
  src/test/Assets/TestProjects/Directory.Build.props
  src/test/Directory.Build.props
  src/test/Directory.Build.targets
  src/test/PrepareTestAssets/PrepareTestAssets.proj
  tools-local/tasks/CopyNupkgAndChangeVersion.cs
Labels: area-Infrastructure

#8188 [release/3.0] Infrastructure fixes to allow stabilized builds for 3.0 GA
  Directory.Build.targets
  publish/Directory.Build.props
  publish/prepare-artifacts.proj
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/Directory.Build.targets
  src/pkg/projects/netcoreapp/pkg/legacy/Directory.Build.props
  src/pkg/projects/netcoreapp/pkg/workaround/Microsoft.NETCore.App.pkgproj
  src/pkg/projects/windowsdesktop/pkg/Microsoft.WindowsDesktop.App.pkgproj
  src/test/Assets/TestProjects/Directory.Build.props
  src/test/Directory.Build.props
  src/test/Directory.Build.targets
  src/test/PrepareTestAssets/PrepareTestAssets.proj
  tools-local/tasks/CopyNupkgAndChangeVersion.cs
Labels: area-Infrastructure, tell-mode

#8210 Minor fix in Native Hosting doc
  Documentation/design-docs/native-hosting.md
Labels: area-Host, documentation

#8279 Add internal build support
  azure-pipelines.yml
  eng/install-nuget-credprovider-then-build.sh
  eng/install-nuget-credprovider-then-msbuild.sh
  eng/install-nuget-credprovider.sh
  eng/jobs/bash-build.yml
  eng/jobs/osx-build.yml
  eng/jobs/prepare-signed-artifacts.yml
  eng/jobs/run-publish-project.yml
  eng/jobs/steps/build-linux-package.yml
  eng/jobs/windows-build.yml
  src/test/Directory.Build.props
  src/test/PrepareTestAssets/PrepareTestAssets.proj
Labels: area-Infrastructure

#8283 Build break fix: internal servicing: match Arcade stage name
  azure-pipelines.yml
Labels: blocking-clean-ci

#8284 Build break fix: Set +x on cred provider build proxy scripts
  eng/install-nuget-credprovider-then-build.sh
  eng/install-nuget-credprovider-then-msbuild.sh
  eng/install-nuget-credprovider.sh
Labels: blocking-clean-ci

#8286 [release/3.0] Add internal build support
  azure-pipelines.yml
  eng/install-nuget-credprovider-then-build.sh
  eng/install-nuget-credprovider-then-msbuild.sh
  eng/install-nuget-credprovider.sh
  eng/jobs/bash-build.yml
  eng/jobs/osx-build.yml
  eng/jobs/prepare-signed-artifacts.yml
  eng/jobs/run-publish-project.yml
  eng/jobs/steps/build-linux-package.yml
  eng/jobs/windows-build.yml
  src/test/Directory.Build.props
  src/test/PrepareTestAssets/PrepareTestAssets.proj
Labels: area-Infrastructure, tell-mode

#8289 Remove the runtime property AppDomainCompatSwitch as it's not used
  src/corehost/cli/hostpolicy/coreclr.cpp
  src/corehost/cli/hostpolicy/coreclr.h
  src/corehost/cli/hostpolicy/hostpolicy_context.cpp
Labels: area-Host

#8290 Make static hostpolicy context a shared pointer
  src/corehost/cli/hostpolicy/hostpolicy.cpp
Labels: area-Host, ask-mode

#8292 Generate cross-arch AppHost pack MSIs
  eng/jobs/windows-build.yml
  src/pkg/packaging-tools/installer.targets
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/windows/bundle/bundle.wxs
  src/pkg/packaging-tools/windows/variables.wxi
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Host.pkgproj
Labels: area-Setup

#8296 Revert "[master] Update dependencies from dotnet/corefx (#8266)"
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: blocking-clean-ci

#8295 [release/3.1] Generate cross-arch AppHost pack MSIs
  eng/jobs/windows-build.yml
  src/pkg/packaging-tools/installer.targets
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/windows/bundle/bundle.wxs
  src/pkg/packaging-tools/windows/variables.wxi
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Host.pkgproj
Labels: area-Setup, ask-mode

#8300 Add missing "--ci" option to Linux build
  eng/jobs/steps/build-linux-package.yml
Labels: area-Infrastructure

#8302 [release/3.1] Add missing "--ci" option to Linux build
  eng/jobs/steps/build-linux-package.yml
Labels: area-Infrastructure, tell-mode

#8293 Move ComHost generation from dotnet/sdk to Microsoft.NET.HostModel
  Microsoft.DotNet.CoreSetup.sln
  Subsets.props
  src/managed/Microsoft.NET.HostModel/ComHost/ClsidMap.cs
  src/managed/Microsoft.NET.HostModel/ComHost/ComHost.cs
  src/managed/Microsoft.NET.HostModel/ComHost/ComHostCustomizationUnsupportedOSException.cs
  src/managed/Microsoft.NET.HostModel/ComHost/ConflictingGuidException.cs
  src/managed/Microsoft.NET.HostModel/ComHost/MissingGuidException.cs
  src/managed/Microsoft.NET.HostModel/ComHost/RegFreeComManifest.cs
  src/managed/Microsoft.NET.HostModel/Microsoft.NET.HostModel.csproj
  src/managed/Microsoft.NET.HostModel/ResourceUpdater.cs
  src/test/Assets/TestProjects/ComLibrary/ComLibrary.cs
  src/test/Assets/TestProjects/ComLibraryConflictingGuid/ComLibraryConflictingGuid.cs
  src/test/Assets/TestProjects/ComLibraryConflictingGuid/ComLibraryConflictingGuid.csproj
  src/test/Assets/TestProjects/ComLibraryMissingGuid/ComLibraryMissingGuid.cs
  src/test/Assets/TestProjects/ComLibraryMissingGuid/ComLibraryMissingGuid.csproj
  src/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/AppHost.Bundle.Tests.csproj
  src/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleExtractToSpecificPath.cs
  src/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundledAppWithSubDirs.cs
  src/test/Microsoft.NET.HostModel.Tests/Helpers/BundleHelper.cs
  src/test/Microsoft.NET.HostModel.Tests/Helpers/BundleHelper.csproj
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/AppHostUpdateTests.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/Microsoft.NET.HostModel.AppHost.Tests.csproj
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundleExtractRun.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundlerConsistencyTests.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/Microsoft.NET.HostModel.Bundle.Tests.csproj
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/ClsidMapTests.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/Microsoft.NET.HostModel.ComHost.Tests.csproj
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/RegFreeComManifestTests.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/TestDirectory.cs
Labels: area-HostModel

#8309 Fix license headers in HostModel.ComHost code.
  src/managed/Microsoft.NET.HostModel/ComHost/ClsidMap.cs
  src/managed/Microsoft.NET.HostModel/ComHost/ComHost.cs
  src/managed/Microsoft.NET.HostModel/ComHost/ConflictingGuidException.cs
  src/managed/Microsoft.NET.HostModel/ComHost/MissingGuidException.cs
  src/managed/Microsoft.NET.HostModel/ComHost/RegFreeComManifest.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/ClsidMapTests.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/RegFreeComManifestTests.cs
  src/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/TestDirectory.cs
Labels: area-HostModel

#8311 Change post-build yaml param dependsOn => validateDependsOn to match Arcade
  eng/stages/publish.yml
Labels: area-Infrastructure, blocking-clean-ci

#8318 Update Windows Build Instructions to state that VS2019 is supported
  Documentation/building/windows-instructions.md
Labels: area-Infrastructure

#8330 [release/3.0] Upgrade SDK toolset from 3.0 preview6 => GA
  global.json
  src/test/Assets/TestProjects/Directory.Build.targets
Labels: area-Infrastructure, tell-mode

#8333 Fix reference to renamed SDK target in test asset project restore
  src/test/Assets/TestProjects/Directory.Build.targets
Labels: area-Infrastructure

#8351 Update COM-activation.md
  Documentation/design-docs/COM-activation.md
Labels: documentation

#8353 [release/3.0] Keep SemVer v1 in 3.0 servicing builds
  eng/Versions.props
Labels: area-Infrastructure, tell-mode

#8377 [release/3.0] Remove publishing for Dev 3.0, channel no longer exists
  azure-pipelines.yml
Labels: area-Infrastructure, blocking-clean-ci, tell-mode
