Repository dotnet/core-setup, pull requests merged in 2019-08, with the labels that each got.

#7549 [release/3.0] Stop signing apphost.exe and comhost.dll in AppHost pack nupkg
  eng/Signing.props
Labels: area-Infrastructure, ask-mode, blocking-release

#7551 Add support for ProgID registration
  Documentation/design-docs/COM-activation.md
  src/corehost/cli/comhost/clsidmap.cpp
  src/corehost/cli/comhost/comhost.cpp
  src/corehost/cli/comhost/comhost.h
Labels: area-Host, os-windows

#7527 [release/3.0] Fix how we determine line/column from a JsonReaderState (#7510)
  src/managed/Microsoft.Extensions.DependencyModel/UnifiedJsonReader.Utf8JsonReader.cs
  src/test/Microsoft.Extensions.DependencyModel.Tests/DependencyContextJsonReaderTest.cs
Labels: area-Host, ask-mode

#7602 [release/3.0] Reference WPF theme assemblies by default
  src/pkg/projects/windowsdesktop/pkg/Directory.Build.props
  src/test/Microsoft.DotNet.CoreSetup.Packaging.Tests/WindowsDesktopTests.cs
Labels: area-Setup, ask-mode

#7393 [release/3.0] Make apphost.exe and comhost.dll MSI id stable
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Host.pkgproj
  tools-local/tasks/StabilizeWixFileId.cs
Labels: area-Setup, ask-mode

#7584 [release/3.0] Add root "shared" dir to WindowsDesktop zip
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/projects/netcoreapp/sfx/Microsoft.NETCore.App.SharedFx.sfxproj
Labels: area-Setup, ask-mode

#7628 [release/3.0] Skip framework validation for secondary components loaded into a self-contained app
  src/corehost/cli/fxr/fx_muxer.cpp
  src/test/HostActivation.Tests/NativeHosting/HostContext.cs
Labels: area-Host, ask-mode

#7573 Add support for ProgID registration (3.0)
  Documentation/design-docs/COM-activation.md
  src/corehost/cli/comhost/clsidmap.cpp
  src/corehost/cli/comhost/comhost.cpp
  src/corehost/cli/comhost/comhost.h
Labels: area-Host, ask-mode, os-windows

#7654 HostWriter: Update Retry-count
  src/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
Labels: area-HostModel

#7660 Adds PresentationUI.dll to WPF Profile
  eng/Version.Details.xml
  eng/Versions.props
  src/pkg/projects/windowsdesktop/pkg/Directory.Build.props
Labels: area-Setup, ask-mode

#7638 [release/3.0] HostWriter: Retry updates on IO error (#7617)
  src/managed/Microsoft.NET.HostModel/AppHost/HResultException.cs
  src/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
  src/managed/Microsoft.NET.HostModel/AppHost/ResourceUpdater.cs
  src/managed/Microsoft.NET.HostModel/AppHost/RetryUtil.cs
Labels: area-HostModel, ask-mode

#7725 Switch to Arcade yaml stage-based publishing with custom steps
  azure-pipelines.yml
  eng/Versions.props
  eng/common/post-build/darc-gather-drop.ps1
  eng/common/templates/post-build/channels/internal-servicing.yml
  eng/common/templates/post-build/channels/netcore-dev-5.yml
  eng/common/templates/post-build/channels/netcore-tools-latest.yml
  eng/common/templates/post-build/channels/public-dev-release.yml
  eng/common/templates/post-build/channels/public-release.yml
  eng/common/templates/post-build/channels/public-validation-release.yml
  eng/common/templates/post-build/post-build.yml
  eng/jobs/finalize-publish.yml
  eng/jobs/prepare-signed-artifacts.yml
  eng/jobs/steps/upload-job-artifacts.yml
  eng/stages/custom-publish.yml
  publish/Directory.Build.props
  publish/Directory.Build.targets
  publish/custom-publish.proj
  publish/prepare-artifacts.proj
  publish/publish.proj
Labels: area-Infrastructure

#6968 HostModel:Enable TestWithAdditionalContentAfterBundleMetadata
  src/test/BundleTests/Microsoft.NET.HostModel.Bundle.Tests/BundlerConsistencyTests.cs
Labels: area-HostModel

#7658 SharedHost always installs to 'ProgramFiles'\dotnet
  src/pkg/projects/Microsoft.NETCore.DotNetHost/host.wxs
Labels: area-Setup

#7754 Temporary build break fix: move eng/common symbol publish to a pool with space
  eng/common/templates/post-build/channels/netcore-dev-5.yml
Labels: blocking-clean-ci

#7758 Use existing .NET Core Runtime installer localization for Windows Desktop Runtime
  src/pkg/projects/windowsdesktop/sfx/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1028/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1029/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1031/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1033/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1036/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1040/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1041/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1042/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1045/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1046/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1049/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/1055/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/2052/bundle.wxl
  src/pkg/projects/windowsdesktop/sfx/theme/3082/bundle.wxl
Labels: area-Setup

#7765 Add single quotes to warnAsError:false to fix official build break during symbol publish
  azure-pipelines.yml
Labels: blocking-clean-ci

#6576 Single-File: MemoryMap the bundle file
  src/corehost/cli/apphost/CMakeLists.txt
  src/corehost/cli/apphost/bundle/bundle_runner.cpp
  src/corehost/cli/apphost/bundle/bundle_runner.h
  src/corehost/cli/apphost/bundle/dir_utils.cpp
  src/corehost/cli/apphost/bundle/dir_utils.h
  src/corehost/cli/apphost/bundle/extractor.cpp
  src/corehost/cli/apphost/bundle/extractor.h
  src/corehost/cli/apphost/bundle/file_entry.cpp
  src/corehost/cli/apphost/bundle/file_entry.h
  src/corehost/cli/apphost/bundle/header.cpp
  src/corehost/cli/apphost/bundle/header.h
  src/corehost/cli/apphost/bundle/manifest.cpp
  src/corehost/cli/apphost/bundle/manifest.h
  src/corehost/cli/apphost/bundle/reader.cpp
  src/corehost/cli/apphost/bundle/reader.h
  src/corehost/cli/apphost/bundle/runner.cpp
  src/corehost/cli/apphost/bundle/runner.h
  src/corehost/common/pal.h
  src/corehost/common/pal.unix.cpp
  src/corehost/common/pal.windows.cpp
  src/corehost/corehost.cpp
Labels: area-Host

#7766 SharedHost always installs to 'ProgramFiles'\dotnet; 3.0
  src/pkg/packaging/windows/host/host.wxs
Labels: area-Setup, ask-mode

#7767 [release/3.0] Increase bundle's button size: avoid loc clipping
  src/pkg/projects/netcoreapp/sfx/bundle.thm
  src/pkg/projects/windowsdesktop/sfx/bundle.thm
Labels: area-Setup, ask-mode

#7776 Categorize shipping/nonshipping NuGet packages
  publish/Directory.Build.targets
  publish/prepare-artifacts.proj
  src/pkg/packaging-tools/framework.sharedfx.props
  src/pkg/projects/netcoreapp/pkg/legacy/Directory.Build.props
  src/pkg/projects/netcoreapp/pkg/workaround/Microsoft.NETCore.App.pkgproj
  src/pkg/projects/windowsdesktop/pkg/Microsoft.WindowsDesktop.App.pkgproj
  src/test/Assets/TestProjects/Directory.Build.props
  src/test/PrepareTestAssets/PrepareTestAssets.proj
Labels: area-Setup

#7779 Split blob publish into stages run before Arcade
  azure-pipelines.yml
  eng/jobs/run-publish-project.yml
  eng/stages/custom-publish.yml
  eng/stages/publish.yml
  publish/publish-blobs.proj
  publish/publish-final.proj
Labels: area-Infrastructure

#7792 [release/3.0] Categorize shipping/nonshipping NuGet packages
  publish/Directory.Build.targets
  publish/prepare-artifacts.proj
  src/pkg/packaging-tools/framework.sharedfx.props
  src/pkg/projects/netcoreapp/pkg/legacy/Directory.Build.props
  src/pkg/projects/netcoreapp/pkg/workaround/Microsoft.NETCore.App.pkgproj
  src/pkg/projects/windowsdesktop/pkg/Microsoft.WindowsDesktop.App.pkgproj
  src/test/Assets/TestProjects/Directory.Build.props
  src/test/PrepareTestAssets/PrepareTestAssets.proj
Labels: area-Infrastructure, tell-mode

#7796 [release/3.0] Split blob publish into stages run before Arcade
  azure-pipelines.yml
  eng/jobs/run-publish-project.yml
  eng/stages/custom-publish.yml
  eng/stages/publish.yml
  publish/publish-blobs.proj
  publish/publish-final.proj
Labels: area-Infrastructure, tell-mode

#7797 [release/3.0-preview9] Split blob publish into stages run before Arcade
  azure-pipelines.yml
  eng/jobs/run-publish-project.yml
  eng/stages/custom-publish.yml
  eng/stages/publish.yml
  publish/publish-blobs.proj
  publish/publish-final.proj
Labels: area-Infrastructure

#7807 Stop the BAR publish job assigning channel early
  azure-pipelines.yml
Labels: area-Infrastructure

#7808 [release/3.0] Stop the BAR publish job assigning channel early
  azure-pipelines.yml
Labels: area-Infrastructure, tell-mode

#7820 Fix bundle installer signing
  signing/SignBurnBundleFiles.proj
  signing/SignMsiFiles.proj
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/netcoreapp/sfx/Microsoft.NETCore.App.SharedFx.sfxproj
  src/pkg/projects/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.SharedFx.sfxproj
Labels: area-Infrastructure

#7821 [release/3.0] Fix bundle installer signing
  signing/SignBurnBundleFiles.proj
  signing/SignMsiFiles.proj
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/netcoreapp/sfx/Microsoft.NETCore.App.SharedFx.sfxproj
  src/pkg/projects/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.SharedFx.sfxproj
Labels: area-Infrastructure, tell-mode

#7822 [release/3.0-preview9] Fix bundle installer signing
  signing/SignBurnBundleFiles.proj
  signing/SignMsiFiles.proj
  src/pkg/packaging-tools/packaging-tools.targets
  src/pkg/packaging-tools/windows/wix.targets
  src/pkg/projects/netcoreapp/sfx/Microsoft.NETCore.App.SharedFx.sfxproj
  src/pkg/projects/windowsdesktop/sfx/Microsoft.WindowsDesktop.App.SharedFx.sfxproj
Labels: area-Infrastructure, blocking-release

#7892 Update readme's 3.0 column for the consolidated runtime-deps Debian packages
  README.md
Labels: area-Setup

#7897 Fix source-build patch and "RestoreAllBuildRids=false" workaround argument
  src/pkg/packaging-tools/framework.sharedfx.targets
  src/pkg/projects/Directory.Build.props
  src/pkg/projects/windowsdesktop/Directory.Build.props
Labels: area-Infrastructure
