Repository dotnet/core-setup, pull requests merged in 2022-04, with the labels that each got.

#9201 Build DependencyModel in May
  eng/Versions.props
Labels: tell-mode

#9204 Enable installation on Ubuntu 22.04
  src/pkg/packaging/deb/package.targets
Labels: Servicing-approved

#9207 Revert "Enable installation on Ubuntu 22.04"
  src/pkg/packaging/deb/package.targets
Labels: Servicing-consider
